import { REFERENCE_SOURCES } from "./sources";
import type { PhysicalConstant } from "./types";

const sourceId = REFERENCE_SOURCES.codata2022.id;

/**
 * A deliberately small offline subset of NIST Web Version 9.0 (2022 CODATA).
 * `value` is an SI-friendly JavaScript number; `displayValue` preserves the
 * significant digits published by NIST.
 */
export const CODATA_CONSTANTS: readonly PhysicalConstant[] = [
  {
    id: "speed-of-light",
    name: "Speed of light in vacuum",
    symbol: "c",
    value: 299_792_458,
    displayValue: "299 792 458",
    unit: "m s⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["lightspeed", "vacuum light speed"],
    sourceId,
  },
  {
    id: "planck-constant",
    name: "Planck constant",
    symbol: "h",
    value: 6.626_070_15e-34,
    displayValue: "6.626 070 15 × 10⁻³⁴",
    unit: "J Hz⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["planck"],
    sourceId,
  },
  {
    id: "reduced-planck-constant",
    name: "Reduced Planck constant",
    symbol: "ℏ",
    value: 1.054_571_817e-34,
    displayValue: "1.054 571 817… × 10⁻³⁴",
    unit: "J s",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["h-bar", "hbar"],
    sourceId,
  },
  {
    id: "elementary-charge",
    name: "Elementary charge",
    symbol: "e",
    value: 1.602_176_634e-19,
    displayValue: "1.602 176 634 × 10⁻¹⁹",
    unit: "C",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["electron charge magnitude"],
    sourceId,
  },
  {
    id: "boltzmann-constant",
    name: "Boltzmann constant",
    symbol: "k",
    value: 1.380_649e-23,
    displayValue: "1.380 649 × 10⁻²³",
    unit: "J K⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["k-b", "thermal constant"],
    sourceId,
  },
  {
    id: "avogadro-constant",
    name: "Avogadro constant",
    symbol: "Nₐ",
    value: 6.022_140_76e23,
    displayValue: "6.022 140 76 × 10²³",
    unit: "mol⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["avogadro number", "n a"],
    sourceId,
  },
  {
    id: "molar-gas-constant",
    name: "Molar gas constant",
    symbol: "R",
    value: 8.314_462_618,
    displayValue: "8.314 462 618…",
    unit: "J mol⁻¹ K⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["ideal gas constant", "gas constant"],
    sourceId,
  },
  {
    id: "faraday-constant",
    name: "Faraday constant",
    symbol: "F",
    value: 96_485.332_12,
    displayValue: "96 485.332 12…",
    unit: "C mol⁻¹",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["faraday"],
    sourceId,
  },
  {
    id: "vacuum-electric-permittivity",
    name: "Vacuum electric permittivity",
    symbol: "ε₀",
    value: 8.854_187_818_8e-12,
    displayValue: "8.854 187 8188(14) × 10⁻¹²",
    unit: "F m⁻¹",
    relativeStandardUncertainty: "1.6 × 10⁻¹⁰",
    exact: false,
    aliases: ["electric constant", "epsilon zero", "permittivity of free space"],
    sourceId,
  },
  {
    id: "vacuum-magnetic-permeability",
    name: "Vacuum magnetic permeability",
    symbol: "μ₀",
    value: 1.256_637_061_27e-6,
    displayValue: "1.256 637 061 27(20) × 10⁻⁶",
    unit: "N A⁻²",
    relativeStandardUncertainty: "1.6 × 10⁻¹⁰",
    exact: false,
    aliases: ["magnetic constant", "mu zero", "permeability of free space"],
    sourceId,
  },
  {
    id: "newtonian-gravitation",
    name: "Newtonian constant of gravitation",
    symbol: "G",
    value: 6.674_30e-11,
    displayValue: "6.674 30(15) × 10⁻¹¹",
    unit: "m³ kg⁻¹ s⁻²",
    relativeStandardUncertainty: "2.2 × 10⁻⁵",
    exact: false,
    aliases: ["gravitational constant", "gravity constant"],
    sourceId,
  },
  {
    id: "electron-mass",
    name: "Electron mass",
    symbol: "mₑ",
    value: 9.109_383_713_9e-31,
    displayValue: "9.109 383 7139(28) × 10⁻³¹",
    unit: "kg",
    relativeStandardUncertainty: "3.1 × 10⁻¹⁰",
    exact: false,
    aliases: ["rest mass electron"],
    sourceId,
  },
  {
    id: "proton-mass",
    name: "Proton mass",
    symbol: "mₚ",
    value: 1.672_621_925_95e-27,
    displayValue: "1.672 621 925 95(52) × 10⁻²⁷",
    unit: "kg",
    relativeStandardUncertainty: "3.1 × 10⁻¹⁰",
    exact: false,
    aliases: ["rest mass proton"],
    sourceId,
  },
  {
    id: "atomic-mass-constant",
    name: "Atomic mass constant",
    symbol: "mᵤ",
    value: 1.660_539_068_92e-27,
    displayValue: "1.660 539 068 92(52) × 10⁻²⁷",
    unit: "kg",
    relativeStandardUncertainty: "3.1 × 10⁻¹⁰",
    exact: false,
    aliases: ["unified atomic mass unit", "dalton", "amu"],
    sourceId,
  },
  {
    id: "stefan-boltzmann-constant",
    name: "Stefan–Boltzmann constant",
    symbol: "σ",
    value: 5.670_374_419e-8,
    displayValue: "5.670 374 419… × 10⁻⁸",
    unit: "W m⁻² K⁻⁴",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["stefan boltzmann"],
    sourceId,
  },
  {
    id: "standard-atmosphere",
    name: "Standard atmosphere",
    symbol: "atm",
    value: 101_325,
    displayValue: "101 325",
    unit: "Pa",
    relativeStandardUncertainty: "exact",
    exact: true,
    aliases: ["atmospheric pressure"],
    sourceId,
  },
] as const;

export function getPhysicalConstant(idOrSymbol: string): PhysicalConstant | undefined {
  const needle = idOrSymbol.trim().toLocaleLowerCase("en");
  return CODATA_CONSTANTS.find(
    (constant) =>
      constant.id === needle || constant.symbol.toLocaleLowerCase("en") === needle,
  );
}
